name: dem
channels:
  - conda-forge
  - nodefaults  # force everything to come from conda-forge channel
dependencies:
  - python==3.10.10
  - gdal==3.6.3 
  - sardem~=0.11 
  - dask==2023.3.2 
  - proj-data==1.13 # could not find; did not use
  - sarsen==0.9.3
  - rasterio==1.3.6
  - pystac==1.10.1
  - numpy==1.26.4
