# Input params for OGC application package generator
# The information provided in this file supports CWL and OGC best practices
algorithm_description: This application is designed to process Synthetic Aperture Radar (SAR) data from Sentinel-1 GRD (Ground Range Detected) products using a Digital Elevation Model (DEM) obtained from Copernicus.
algorithm_name: sardem-sarsen-mlucas-01
algorithm_version: mlucas_nasa-ogc
keywords: ogc, sar
code_repository: https://github.com/MAAP-Project/sardem-sarsen.git
citation: https://github.com/MAAP-Project/sardem-sarsen.git
author: arthurduf
contributor: arthurduf
license: https://github.com/MAAP-Project/sardem-sarsen/blob/main/LICENSE
release_notes: None
run_command: /sardem-sarsen/sardem-sarsen.sh
ram_min: 5 # mebibytes
cores_min: 1
outdir_max: 20 # mebibytes

inputs:
  - name: bbox
    doc: Bounding box as 'LEFT BOTTOM RIGHT TOP'
    label: Bounding box
    type: string
    default: -118.06817 34.22169 -118.05801 34.22822
  - name: sentinel_granule
    doc: Sentinel granule URL
    label: Sentinel granule URL
    type: Directory
    default: https://cmr.earthdata.nasa.gov/stac/ASF/collections/SENTINEL-1A_DP_GRD_HIGH_1/items/S1A_[…]20250330T171421_20250330T171446_058537_073E4F_985B-GRD_HD
  - name: stac_asset_name
    doc: STAC asset name
    label: asset name
    type: string?
    default: edu/GRD_HD/SA/S1A_IW_GRDH_1SDV_20250330T171421_20250330T171446_058537_073E4F_985B

outputs:
  - name: out
    type: Directory
