algorithm_description: sardem-sarsen algorithm
algorithm_name: sardem-sarsen
algorithm_version: 0.1.0
repository_url: https://github.com/MAAP-Project/sardem-sarsen.git
docker_container_url: ''
disk_space: 20GB
queue: ''
run_command: sardem-sarsen.sh
inputs:
  config: []
  file: []
  positional:
  - name: bbox
    description: Bounding box as 'LEFT BOTTOM RIGHT TOP'
    default: ''
    required: true
  - name: stac_catalog_folder
    description: STAC catalog folder
    default: ''
    required: false
    type: Directory
  - name: o
    description: Output directory
    default: ''
    required: false
    type: Directory
