on:
  push:
    branches:
      - nasa-ogc
jobs:
  build_app_pack:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Use OGC App Pack Generator Action
        uses: MAAP-Project/ogc-app-pack-generator@chore/docs
        with:
          # Specify action inputs
          config-file-path: nasa/ogc/algorithm_config.yml
          cwl-workflow-dir: cwl
          dockerfile-path: nasa/Dockerfile
          deploy-app-pack: true
          app-pack-register-endpoint: https://api.uat.maap-project.org/api/ogc/processes
        env:
          # MAAP token is required to deploy the algorithm to the MAAP
          MAAP_TOKEN: ${{ secrets.MAAP_TOKEN }}